package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/joho/godotenv"
	_ "github.com/lib/pq"
	_ "modernc.org/sqlite"
)

func main() {
	_ = godotenv.Load(".env")
	pgURL := os.Getenv("DATABASE_URL")
	if pgURL == "" {
		log.Fatal("DATABASE_URL is not set")
	}

	sqlitePath := "./ubt.db"
	if _, err := os.Stat(sqlitePath); os.IsNotExist(err) {
		log.Fatalf("SQLite database %s does not exist", sqlitePath)
	}

	fmt.Println("🚀 Opening SQLite database (read-only)...")
	sqliteDB, err := sql.Open("sqlite", "file:"+sqlitePath+"?mode=ro")
	if err != nil {
		log.Fatalf("Failed to open SQLite: %v", err)
	}
	defer sqliteDB.Close()

	fmt.Println("🚀 Connecting to Neon PostgreSQL...")
	pgDB, err := sql.Open("postgres", pgURL)
	if err != nil {
		log.Fatalf("Failed to open Postgres: %v", err)
	}
	defer pgDB.Close()

	if err := pgDB.Ping(); err != nil {
		log.Fatalf("Postgres ping failed: %v", err)
	}
	fmt.Println("✅ Successfully connected to Neon PostgreSQL!")

	// 1. Create tables in PostgreSQL
	fmt.Println("📦 Creating schema and tables in Neon PostgreSQL...")
	schemaStatements := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			username      TEXT        NOT NULL,
			email         TEXT        NOT NULL UNIQUE,
			password_hash TEXT        NOT NULL,
			role          TEXT        NOT NULL CHECK(role IN ('student', 'teacher')),
			created_at    TIMESTAMPTZ NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`,

		`CREATE TABLE IF NOT EXISTS lessons (
			id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			teacher_id BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			title      TEXT        NOT NULL,
			content    TEXT        NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_lessons_teacher ON lessons(teacher_id)`,

		`CREATE TABLE IF NOT EXISTS questions (
			id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			lesson_id      BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
			position       INT    NOT NULL DEFAULT 0,
			text           TEXT   NOT NULL,
			option_a       TEXT   NOT NULL,
			option_b       TEXT   NOT NULL,
			option_c       TEXT   NOT NULL,
			option_d       TEXT   NOT NULL,
			correct_option TEXT   NOT NULL CHECK(correct_option IN ('A','B','C','D'))
		)`,
		`CREATE INDEX IF NOT EXISTS idx_questions_lesson ON questions(lesson_id)`,

		`CREATE TABLE IF NOT EXISTS student_attempts (
			id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			student_id   BIGINT      NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
			lesson_id    BIGINT      NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
			score        INT         NOT NULL DEFAULT 0,
			total        INT         NOT NULL DEFAULT 0,
			completed_at TIMESTAMPTZ NOT NULL,
			UNIQUE(student_id, lesson_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_attempts_student ON student_attempts(student_id)`,

		`CREATE TABLE IF NOT EXISTS materials (
			id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			teacher_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			title         TEXT        NOT NULL,
			filename      TEXT        NOT NULL,
			original_name TEXT        NOT NULL,
			file_type     TEXT        NOT NULL,
			file_size     BIGINT      NOT NULL DEFAULT 0,
			created_at    TIMESTAMPTZ NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_materials_teacher ON materials(teacher_id)`,

		`CREATE TABLE IF NOT EXISTS material_views (
			id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			material_id BIGINT      NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
			student_id  BIGINT      NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
			viewed_at   TIMESTAMPTZ NOT NULL,
			UNIQUE(material_id, student_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_views_material ON material_views(material_id)`,

		`CREATE TABLE IF NOT EXISTS ai_quizzes (
			id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			material_id BIGINT      NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
			teacher_id  BIGINT      NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
			title       TEXT        NOT NULL,
			difficulty  TEXT        NOT NULL CHECK(difficulty IN ('easy','medium','hard')),
			created_at  TIMESTAMPTZ NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_ai_quizzes_material ON ai_quizzes(material_id)`,

		`CREATE TABLE IF NOT EXISTS ai_questions (
			id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			quiz_id        BIGINT NOT NULL REFERENCES ai_quizzes(id) ON DELETE CASCADE,
			position       INT    NOT NULL DEFAULT 0,
			text           TEXT   NOT NULL,
			option_a       TEXT   NOT NULL,
			option_b       TEXT   NOT NULL,
			option_c       TEXT   NOT NULL,
			option_d       TEXT   NOT NULL,
			correct_option TEXT   NOT NULL CHECK(correct_option IN ('A','B','C','D')),
			explanation    TEXT   NOT NULL DEFAULT ''
		)`,
		`CREATE INDEX IF NOT EXISTS idx_ai_questions_quiz ON ai_questions(quiz_id)`,

		`CREATE TABLE IF NOT EXISTS ai_quiz_attempts (
			id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			student_id   BIGINT      NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
			quiz_id      BIGINT      NOT NULL REFERENCES ai_quizzes(id) ON DELETE CASCADE,
			score        INT         NOT NULL DEFAULT 0,
			total        INT         NOT NULL DEFAULT 0,
			completed_at TIMESTAMPTZ NOT NULL,
			UNIQUE(student_id, quiz_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_ai_attempts_student ON ai_quiz_attempts(student_id)`,

		`CREATE TABLE IF NOT EXISTS student_seen_questions (
			id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			student_id  BIGINT      NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
			quiz_id     BIGINT      NOT NULL REFERENCES ai_quizzes(id)    ON DELETE CASCADE,
			question_id BIGINT      NOT NULL REFERENCES ai_questions(id)  ON DELETE CASCADE,
			seen_at     TIMESTAMPTZ NOT NULL,
			UNIQUE(student_id, question_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_seen_student ON student_seen_questions(student_id, quiz_id)`,

		`CREATE TABLE IF NOT EXISTS sessions (
			id         TEXT        PRIMARY KEY,
			user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			role       TEXT        NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at)`,
	}

	for _, stmt := range schemaStatements {
		if _, err := pgDB.Exec(stmt); err != nil {
			log.Fatalf("Schema error: %v\nQuery: %s", err, stmt)
		}
	}
	fmt.Println("✅ Schema created successfully in PostgreSQL!")

	// 2. Migrate each table in dependency order
	// 2.1 users
	{
		rows, err := sqliteDB.Query("SELECT id, username, email, password_hash, role, created_at FROM users ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query users failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id int64
			var username, email, passwordHash, role string
			var createdAt time.Time
			if err := rows.Scan(&id, &username, &email, &passwordHash, &role, &createdAt); err != nil {
				log.Fatalf("Scan user failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO users (id, username, email, password_hash, role, created_at)
				VALUES ($1, $2, $3, $4, $5, $6)
				ON CONFLICT (id) DO UPDATE SET
					username = EXCLUDED.username,
					email = EXCLUDED.email,
					password_hash = EXCLUDED.password_hash,
					role = EXCLUDED.role,
					created_at = EXCLUDED.created_at
			`, id, username, email, passwordHash, role, createdAt)
			if err != nil {
				log.Fatalf("Insert user %s failed: %v", email, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d users\n", count)
	}

	// 2.2 lessons
	{
		rows, err := sqliteDB.Query("SELECT id, teacher_id, title, content, created_at FROM lessons ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query lessons failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, teacherID int64
			var title, content string
			var createdAt time.Time
			if err := rows.Scan(&id, &teacherID, &title, &content, &createdAt); err != nil {
				log.Fatalf("Scan lesson failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO lessons (id, teacher_id, title, content, created_at)
				VALUES ($1, $2, $3, $4, $5)
				ON CONFLICT (id) DO UPDATE SET
					teacher_id = EXCLUDED.teacher_id,
					title = EXCLUDED.title,
					content = EXCLUDED.content,
					created_at = EXCLUDED.created_at
			`, id, teacherID, title, content, createdAt)
			if err != nil {
				log.Fatalf("Insert lesson %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d lessons\n", count)
	}

	// 2.3 questions
	{
		rows, err := sqliteDB.Query("SELECT id, lesson_id, position, text, option_a, option_b, option_c, option_d, correct_option FROM questions ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query questions failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, lessonID int64
			var position int
			var text, optA, optB, optC, optD, correctOpt string
			if err := rows.Scan(&id, &lessonID, &position, &text, &optA, &optB, &optC, &optD, &correctOpt); err != nil {
				log.Fatalf("Scan question failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO questions (id, lesson_id, position, text, option_a, option_b, option_c, option_d, correct_option)
				VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
				ON CONFLICT (id) DO UPDATE SET
					lesson_id = EXCLUDED.lesson_id,
					position = EXCLUDED.position,
					text = EXCLUDED.text,
					option_a = EXCLUDED.option_a,
					option_b = EXCLUDED.option_b,
					option_c = EXCLUDED.option_c,
					option_d = EXCLUDED.option_d,
					correct_option = EXCLUDED.correct_option
			`, id, lessonID, position, text, optA, optB, optC, optD, correctOpt)
			if err != nil {
				log.Fatalf("Insert question %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d questions\n", count)
	}

	// 2.4 student_attempts
	{
		rows, err := sqliteDB.Query("SELECT id, student_id, lesson_id, score, total, completed_at FROM student_attempts ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query student_attempts failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, studentID, lessonID int64
			var score, total int
			var completedAt time.Time
			if err := rows.Scan(&id, &studentID, &lessonID, &score, &total, &completedAt); err != nil {
				log.Fatalf("Scan attempt failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO student_attempts (id, student_id, lesson_id, score, total, completed_at)
				VALUES ($1, $2, $3, $4, $5, $6)
				ON CONFLICT (id) DO UPDATE SET
					score = EXCLUDED.score,
					total = EXCLUDED.total,
					completed_at = EXCLUDED.completed_at
			`, id, studentID, lessonID, score, total, completedAt)
			if err != nil {
				log.Fatalf("Insert student_attempt %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d student_attempts\n", count)
	}

	// 2.5 materials
	{
		rows, err := sqliteDB.Query("SELECT id, teacher_id, title, filename, original_name, file_type, file_size, created_at FROM materials ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query materials failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, teacherID, fileSize int64
			var title, filename, origName, fileType string
			var createdAt time.Time
			if err := rows.Scan(&id, &teacherID, &title, &filename, &origName, &fileType, &fileSize, &createdAt); err != nil {
				log.Fatalf("Scan material failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO materials (id, teacher_id, title, filename, original_name, file_type, file_size, created_at)
				VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
				ON CONFLICT (id) DO UPDATE SET
					teacher_id = EXCLUDED.teacher_id,
					title = EXCLUDED.title,
					filename = EXCLUDED.filename,
					original_name = EXCLUDED.original_name,
					file_type = EXCLUDED.file_type,
					file_size = EXCLUDED.file_size,
					created_at = EXCLUDED.created_at
			`, id, teacherID, title, filename, origName, fileType, fileSize, createdAt)
			if err != nil {
				log.Fatalf("Insert material %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d materials\n", count)
	}

	// 2.6 material_views
	{
		rows, err := sqliteDB.Query("SELECT id, material_id, student_id, viewed_at FROM material_views ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query material_views failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, materialID, studentID int64
			var viewedAt time.Time
			if err := rows.Scan(&id, &materialID, &studentID, &viewedAt); err != nil {
				log.Fatalf("Scan material_view failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO material_views (id, material_id, student_id, viewed_at)
				VALUES ($1, $2, $3, $4)
				ON CONFLICT (id) DO UPDATE SET
					viewed_at = EXCLUDED.viewed_at
			`, id, materialID, studentID, viewedAt)
			if err != nil {
				log.Fatalf("Insert material_view %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d material_views\n", count)
	}

	// 2.7 ai_quizzes
	{
		rows, err := sqliteDB.Query("SELECT id, material_id, teacher_id, title, difficulty, created_at FROM ai_quizzes ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query ai_quizzes failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, materialID, teacherID int64
			var title, difficulty string
			var createdAt time.Time
			if err := rows.Scan(&id, &materialID, &teacherID, &title, &difficulty, &createdAt); err != nil {
				log.Fatalf("Scan ai_quiz failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO ai_quizzes (id, material_id, teacher_id, title, difficulty, created_at)
				VALUES ($1, $2, $3, $4, $5, $6)
				ON CONFLICT (id) DO UPDATE SET
					material_id = EXCLUDED.material_id,
					teacher_id = EXCLUDED.teacher_id,
					title = EXCLUDED.title,
					difficulty = EXCLUDED.difficulty,
					created_at = EXCLUDED.created_at
			`, id, materialID, teacherID, title, difficulty, createdAt)
			if err != nil {
				log.Fatalf("Insert ai_quiz %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d ai_quizzes\n", count)
	}

	// 2.8 ai_questions
	{
		rows, err := sqliteDB.Query("SELECT id, quiz_id, position, text, option_a, option_b, option_c, option_d, correct_option, explanation FROM ai_questions ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query ai_questions failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, quizID int64
			var position int
			var text, optA, optB, optC, optD, correctOpt, explanation string
			if err := rows.Scan(&id, &quizID, &position, &text, &optA, &optB, &optC, &optD, &correctOpt, &explanation); err != nil {
				log.Fatalf("Scan ai_question failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO ai_questions (id, quiz_id, position, text, option_a, option_b, option_c, option_d, correct_option, explanation)
				VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
				ON CONFLICT (id) DO UPDATE SET
					quiz_id = EXCLUDED.quiz_id,
					position = EXCLUDED.position,
					text = EXCLUDED.text,
					option_a = EXCLUDED.option_a,
					option_b = EXCLUDED.option_b,
					option_c = EXCLUDED.option_c,
					option_d = EXCLUDED.option_d,
					correct_option = EXCLUDED.correct_option,
					explanation = EXCLUDED.explanation
			`, id, quizID, position, text, optA, optB, optC, optD, correctOpt, explanation)
			if err != nil {
				log.Fatalf("Insert ai_question %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d ai_questions\n", count)
	}

	// 2.9 ai_quiz_attempts
	{
		rows, err := sqliteDB.Query("SELECT id, student_id, quiz_id, score, total, completed_at FROM ai_quiz_attempts ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query ai_quiz_attempts failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, studentID, quizID int64
			var score, total int
			var completedAt time.Time
			if err := rows.Scan(&id, &studentID, &quizID, &score, &total, &completedAt); err != nil {
				log.Fatalf("Scan ai_quiz_attempt failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO ai_quiz_attempts (id, student_id, quiz_id, score, total, completed_at)
				VALUES ($1, $2, $3, $4, $5, $6)
				ON CONFLICT (id) DO UPDATE SET
					score = EXCLUDED.score,
					total = EXCLUDED.total,
					completed_at = EXCLUDED.completed_at
			`, id, studentID, quizID, score, total, completedAt)
			if err != nil {
				log.Fatalf("Insert ai_quiz_attempt %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d ai_quiz_attempts\n", count)
	}

	// 2.10 student_seen_questions
	{
		rows, err := sqliteDB.Query("SELECT id, student_id, quiz_id, question_id, seen_at FROM student_seen_questions ORDER BY id ASC")
		if err != nil {
			log.Fatalf("Query student_seen_questions failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, studentID, quizID, questionID int64
			var seenAt time.Time
			if err := rows.Scan(&id, &studentID, &quizID, &questionID, &seenAt); err != nil {
				log.Fatalf("Scan seen_question failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO student_seen_questions (id, student_id, quiz_id, question_id, seen_at)
				VALUES ($1, $2, $3, $4, $5)
				ON CONFLICT (id) DO UPDATE SET
					seen_at = EXCLUDED.seen_at
			`, id, studentID, quizID, questionID, seenAt)
			if err != nil {
				log.Fatalf("Insert student_seen_questions %d failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d student_seen_questions\n", count)
	}

	// 2.11 sessions
	{
		rows, err := sqliteDB.Query("SELECT s.id, s.user_id, s.role, s.created_at, s.expires_at FROM sessions s WHERE s.user_id IN (SELECT id FROM users) ORDER BY s.created_at ASC")
		if err != nil {
			log.Fatalf("Query sessions failed: %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			var id, role string
			var userID int64
			var createdAt, expiresAt time.Time
			if err := rows.Scan(&id, &userID, &role, &createdAt, &expiresAt); err != nil {
				log.Fatalf("Scan session failed: %v", err)
			}

			_, err = pgDB.Exec(`
				INSERT INTO sessions (id, user_id, role, created_at, expires_at)
				VALUES ($1, $2, $3, $4, $5)
				ON CONFLICT (id) DO UPDATE SET
					expires_at = EXCLUDED.expires_at
			`, id, userID, role, createdAt, expiresAt)
			if err != nil {
				log.Fatalf("Insert session %s failed: %v", id, err)
			}
			count++
		}
		fmt.Printf("✅ Migrated %d sessions\n", count)
	}

	// 3. Reset sequences so auto-increment works for new rows
	fmt.Println("🔄 Resetting PostgreSQL identity sequences...")
	autoTables := []string{
		"users", "lessons", "questions", "student_attempts",
		"materials", "material_views", "ai_quizzes", "ai_questions",
		"ai_quiz_attempts", "student_seen_questions",
	}

	for _, table := range autoTables {
		query := fmt.Sprintf(`
			SELECT setval(
				pg_get_serial_sequence('%s', 'id'),
				COALESCE((SELECT MAX(id) FROM %s), 1),
				true
			)
		`, table, table)
		if _, err := pgDB.Exec(query); err != nil {
			log.Fatalf("Reset sequence for %s failed: %v", table, err)
		}
	}
	fmt.Println("✅ All sequences updated successfully!")

	// 4. Verification: compare row counts
	fmt.Println("\n📊 VERIFICATION AUDIT (SQLite vs Neon PostgreSQL):")
	allTables := append(autoTables, "sessions")
	allMatched := true

	for _, table := range allTables {
		var sqliteCount, pgCount int64
		countSqliteQ := fmt.Sprintf("SELECT COUNT(*) FROM %s", table)
		if table == "sessions" {
			countSqliteQ = "SELECT COUNT(*) FROM sessions WHERE user_id IN (SELECT id FROM users)"
		}
		if err := sqliteDB.QueryRow(countSqliteQ).Scan(&sqliteCount); err != nil {
			log.Fatalf("Count SQLite %s failed: %v", table, err)
		}
		if err := pgDB.QueryRow(fmt.Sprintf("SELECT COUNT(*) FROM %s", table)).Scan(&pgCount); err != nil {
			log.Fatalf("Count Postgres %s failed: %v", table, err)
		}

		status := "✅ MATCH"
		if sqliteCount != pgCount {
			status = "❌ MISMATCH"
			allMatched = false
		}
		fmt.Printf(" - %-25s | SQLite: %4d | Neon PG: %4d | %s\n", table, sqliteCount, pgCount, status)
	}

	if allMatched {
		fmt.Println("\n🎉 MIGRATION TO NEON POSTGRESQL 100% COMPLETE & VERIFIED!")
	} else {
		log.Fatalf("Data mismatch detected after migration!")
	}
}
